#! /bin/sh

sxhkd &
feh --bg-center ~/pictures/RsiAkuR.jpg &
#panel &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         6
bspc config window_gap          12
bspc config top_padding         0
bspc config left_padding         0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color "#bd93f9"
bspc config normal_border_color "#282a36"

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

bspc rule -a Plasma state=floating
bspc rule -a Plasma-desktop state=floating
bspc rule -a plasmashell state=floating

